name: helper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.1
  dio: ^5.3.3
  fpdart: ^1.1.0
  file_picker: ^6.1.1
  flutter_secure_storage: ^9.0.0
  firebase_storage: ^11.2.8
  flutter_riverpod: ^2.4.3
  timeline_tile_nic: ^2.0.1
  table_calendar: ^3.0.9
  iconsax_flutter: ^1.0.0
  cached_network_image: ^3.3.0
  share_plus: ^7.2.2
  image_picker: ^1.0.4
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  url_launcher: ^6.2.1
  my_formfield: ^0.0.6
  toastification: ^1.1.0
  flutter_spinkit: ^5.2.0
  flutter_linkify: ^6.0.0
  any_link_preview: ^3.0.1
  flex_color_scheme: ^7.3.1
  linkify:
  local_auth: ^2.1.8
  connectivity_plus: ^5.0.2
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/


